apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tiennt220805/My-GitOps-YAS.git
    targetRevision: HEAD
    path: environments/staging/infra-apps
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: yas-staging-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: cart
          - service: tax
          - service: order
          - service: product
          - service: media
          - service: rating
          - service: customer
          - service: location
          - service: inventory
          - service: search
  template:
    metadata:
      name: yas-staging-{{service}}
      labels:
        app.kubernetes.io/part-of: yas-staging
    spec:
      project: default
      source:
        repoURL: https://github.com/tiennt220805/My-GitOps-YAS.git
        targetRevision: HEAD
        path: charts/{{service}}
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - ../../environments/staging/values-shared.yaml
            - ../../environments/staging/services/{{service}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: yas-staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
