apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-dev-keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/tiennt220805/My-GitOps-YAS.git
    targetRevision: HEAD
    path: infrastructure/base/keycloak/keycloak
    helm:
      valueFiles:
        - ../../../../environments/dev/values-shared.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
