backend:
  image:
    repository: thanhtien2208/yas-rating
    tag: main
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  ingress:
    enabled: false
