global:
  domain: ""

keycloak:
  hostname: identity.yas.test.com
  backofficeRedirectUrl: ""
  storefrontRedirectUrl: ""
  bootstrapAdmin:
    username: admin
    password: admin

postgresql:
  host: ""
  username: yasadminuser
  password: admin
