backend:
  image:
    repository: thanhtien2208/yas-tax
    tag: main
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: false
