apiVersion: v1
kind: Secret
metadata:
  name: user-credentials-secret
stringData:
  users: |-
    {{- htpasswd (.Values.elasticsearch.username | default "yas") (.Values.elasticsearch.password | default "changeme") | nindent 4 }}
  users_roles: |-
    superuser:{{ .Values.elasticsearch.username | default "yas" }}
